name: Build and test package

on:
  workflow_call:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install hatch
        uses: pypa/hatch@install

      - name: Test package
        run: hatch test

      - name: Build package  # I think I will eventually remove this step.
        run: hatch build

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
