name: Build and test package

on:
  workflow_call:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install hatch
        uses: pypa/hatch@install

      - name: Test package
        run: hatch test

      - name: Lint package
        run: hatch fmt --check

      - name: Build package
        run: hatch build

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: dist  # TODO: use output of `hatch version` to set this value.
          path: dist
