name: Create release from version tag

on:
  push:
    tags:
      - "*"

jobs:
  build-test:
    name: Build and test package
    uses: ./.github/workflows/build-test.yml

  create-release:
    name: Create the release
    runs-on: ubuntu-latest
    needs:
      - build-test
    steps:
      - name: Install hatch
        uses: pypa/hatch@install

      - name: Validate tag name
        id: validate_tag_name
        continue-on-error: true
        run: hatch run release:validate-tag

      - name: Fetch package artifact
        id: download
        uses: actions/download-artifact@v4

      - name: Create release
        if: ${{ steps.validate_tag_name.outcome == 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          validate_tag_name: ${{ env.GITHUB_REF_NAME }}
          files: ${{steps.download.outputs.download-path}}/*

      - name: Publish package to PyPI
        if: ${{ steps.validate_tag_name.outcome == 'success' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ${{steps.download.outputs.download-path}}
