name: Create release from version tag

on:
  push:
    tags:
      - "*"

jobs:
  build-test:
    name: Build and test package
    uses: ./.github/workflows/build-test.yml

  create-release:
    name: Create the release
    runs-on: ubuntu-latest
    needs:
      - build-test
    steps:
      - name: Install dependencies
        run: pip install dunamai

      - name: Get tag name
        id: tag_name
        continue-on-error: true
        run: dunamai check --style pep440 $(echo $GITHUB_REF_NAME | sed 's/^v//')

      - name: Fetch package artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Create release
        if: ${{ steps.tag_name.outcome == 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          files: ${{steps.download.outputs.download-path}}/*

      - name: Publish package to PyPI
        if: ${{ steps.tag_name.outcome == 'success' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ${{steps.download.outputs.download-path}}
