name: Create release from version tag

on:
  push:
    tags:
      - "*"

jobs:
  build-test:
    name: Build and test package
    uses: ./.github/workflows/build-test.yml

  create-release:
    name: Create the release
    runs-on: ubuntu-latest
    needs:
      - build-test
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install hatch
        uses: pypa/hatch@install

      - name: List tag name
        run: hatch run release:list-github-ref-name

      - name: Validate tag name
        id: validate_tag_name
        continue-on-error: true
        run: hatch run release:validate-tag

      - name: Fetch package artifact
        id: download
        uses: actions/download-artifact@v4

      - name: Create release
        if: ${{ steps.validate_tag_name.outcome == 'success' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          files: ${{steps.download.outputs.download-path}}/dist/*
          # TODO: The above value was determined by guess and check; I
          # should be more precise and I need to fix it.

      - name: Publish package to PyPI
        if: ${{ steps.validate_tag_name.outcome == 'success' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{steps.download.outputs.download-path}}/dist
          # TODO: The above value was determined by guess and check; I
          # should be more precise and I need to fix it.
